version: '3'

services:
  anaconda:
    container_name: data_science_anaconda
    build: .
    ports:
      - 80:8888
    volumes:
      - ./notebooks:/opt/notebooks/
      - ./original_data:/opt/original_data/
      - ./transformed_data:/opt/transformed_data/
