version: '3'

services:
  anaconda:
    container_name: data_science_anaconda
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/opt/notebooks/
      - ./original_data:/opt/original_data/
      - ./transformed_data:/opt/transformed_data/

  api:
    container_name: data_science_api
    build: ./api
    ports:
      - 5000:5000
    volumes:
      - ./transformed_data:/app/transformed_data/
      - ./api/routes:/app/routes/
      - ./api/scripts:/app/scripts/

  frontend:
    container_name: data_science_frontend_proxy
    image: nginx
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - api
      - anaconda
